# Generated by Django 2.0.1 on 2018-01-24 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books_explorers', '0003_auto_20180123_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors_work', models.CharField(max_length=200)),
                ('author_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books_explorers.Author')),
            ],
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
